name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '18.16'

      - name: Install node modules
        run: |
          npm install

      - name: Run unit tests
        run: |
          npm test -- --coverage
